apiVersion: v1
kind: ConfigMap
metadata:
  name: kiii-proekt-config
  namespace: kiii-proekt
data:
  DATASOURCE_USERNAME: temp
  DATASOURCE_URL: jdbc:mysql://mysql.kiii-proekt.svc.cluster.local:3306/db