apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: kiii-proekt
data:
  MYSQL_DATABASE: db
  MYSQL_USER: temp
  initialize.sh: |
    #!/bin/bash
    if [ $(hostname) = "mysql-0" ]; then
      echo "Bootstrapping the group replication..."
      mysql -uroot -p$MYSQL_ROOT_PASSWORD <<EOF
      SET GLOBAL group_replication_bootstrap_group=ON;
      START GROUP_REPLICATION;
      SET GLOBAL group_replication_bootstrap_group=OFF;
      EOF
    else
      echo "Joining existing group replication..."
      mysql -uroot -p$MYSQL_ROOT_PASSWORD <<EOF
      START GROUP_REPLICATION;
      EOF
    fi