apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: kiii-proekt
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
data:
  primary.cnf: |
    # Apply this config only on the primary.
    [mysqld]
    log-bin    
    gtid_mode = ON
    enforce-gtid-consistency = TRUE
  replica.cnf: |
    # Apply this config only on replicas.
    [mysqld]
    super-read-only
    gtid_mode = ON
    enforce-gtid-consistency = TRUE