apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-router
  namespace: kiii-proekt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-router
  template:
    metadata:
      labels:
        app: mysql-router
    spec:
      containers:
      - name: mysql-router
        image: mysql/mysql-router:8.0
        env:
        - name: MYSQL_HOST
          value: "mysql-0.mysql"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 6446
