apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: kiii
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None  # Headless service
  selector:
    app: mysql-statefulset
